export default {
  medium: "#7c7c82",
  lightBlue: "#5ab5da",
  lightGreen: "#58cd7d",
  red: "red",
  white: "#fff",
  hyperlinkBlue: "#4385f4",
  black: "black",
  lightGray: "#ebeef0",
  darkBlue: "#1f65ff",
  lightPurple: "#cbc3e3",
  lemonYellow: "#fed54a",
  brightMagenta: "#fd297a",
  tourqouise: "#36d7b7",
};
